#!/bin/sh
set -e

. "$HOME/.path/_set"
exec "$("$(dirname -- "$0")/../../_bin/which-after" "$0")" \
 --profile '' \
 --width 960 \
 --height 540 \
 --ntp "$(cat "$(dirname -- "$0")/.ora.local.ntp-server")" \
 "$@"
